/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/HelloWorld copy.vue')['default']
    FilterButton: typeof import('./src/components/FilterButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    'HelloWorld copy': typeof import('./src/components/HelloWorld copy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UContainer: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UError: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Error.vue')['default']
    UHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UPage: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageBody: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue')['default']
    UPageCard: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageGrid: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue')['default']
    UPageHeader: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
    UPagination: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UTimeline: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_a28409819e978fc1925d5beb5c8f2135/node_modules/@nuxt/ui/dist/runtime/components/Timeline.vue')['default']
    WorkflowCard: typeof import('./src/components/WorkflowCard.vue')['default']
    WorkflowDetailsView: typeof import('./src/components/WorkflowDetailsView.vue')['default']
    WorkflowList: typeof import('./src/components/WorkflowList.vue')['default']
    WorkflowsView: typeof import('./src/components/WorkflowsView.vue')['default']
  }
}
